import { Bus, Plane, TrainFront } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { JourneyIcon } from '@/config/types'
import data from '@/config/venue-routes.json'

export interface RouteData {
  distanceKm: number
  durationMin: number
  /** [lat, lng] pairs */
  path: number[][]
}

/** Driving routes generated by `npm run routes` */
export const venueRoutes: Record<string, RouteData | undefined> = data.routes

export const journeyStyles: Record<JourneyIcon, { icon: LucideIcon; color: string }> = {
  plane: { icon: Plane, color: '#d9731a' },
  train: { icon: TrainFront, color: '#35603a' },
  bus: { icon: Bus, color: '#9a6b1f' },
}
